# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=3)),
                ('services', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
            ],
        ),
    ]
