# Generated by Django 2.0.1 on 2018-03-06 01:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('services', models.CharField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 639-3', max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='languages',
            field=models.ManyToManyField(related_name='facilities', to='maps.Language'),
        ),
    ]
