# Generated by Django 2.0.2 on 2018-03-07 20:39

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20180306_0132'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
