# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20161217_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Facility',
        ),
    ]
