# Generated by Django 2.0.2 on 2018-03-07 22:50

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_enable_postgis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='long',
        ),
        migrations.AddField(
            model_name='facility',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0.0, 0.0), geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
