# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20161221_0529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='facility',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='services',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
