# Generated by Django 2.0.1 on 2018-02-14 00:08

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='long',
        ),
        migrations.AddField(
            model_name='facility',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='0.0, 0.0', max_length=100),
            preserve_default=False,
        ),
    ]
