# Generated by Django 2.0.1 on 2018-02-14 00:56

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20180214_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=150),
        ),
    ]
